#!/usr/bin/env bash

# import common utils
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$DIR/../common"

setup_workspace()
echo "hello"
file_name=$(date "+%m-%d-%y.txt")
FULL_PATH=$HOME/Documents/notes/${YEAR}/${MONTH}/${file_name}
if [ -f "$FULL_PATH" ]; then
    open "$FULL_PATH";
    exit 0;
fi

# Write on note
TITLE=$(date "+%A, %B %d, %Y")
echo "Notes for ${TITLE}" > "$FULL_PATH"
open "$FULL_PATH"
