#!/usr/bin/env bash

# import common utils
DIR=$( dirname $( dirname "${BASH_SOURCE[0]}" ) )/common
source $DIR

setup_workspace

file_name=$(date "+%m-%d-%y.txt")
FULL_PATH=$HOME/Documents/notes/${YEAR}/${MONTH}/${file_name}
if [ -f "$FULL_PATH" ]; then
    open "$FULL_PATH";
    exit 0;
fi

# Write on note
TITLE=$(date "+%A, %B %d, %Y")
echo -e "Notes for ${TITLE}\n\nSCRUM\n\n\nPROJECTS" > "$FULL_PATH"
open "$FULL_PATH"

